name: Compatibility Report
description: Report how GameMaker games work in Butterscotch
title: "GAME NAME HERE"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ### Description
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a description of what happens when running the game in Butterscotch describing the issues that you found (or the lack thereof). If possible, include screenshots comparing issues between the original runner vs Butterscotch.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Description
  - type: textarea
    id: url
    attributes:
      label: Game URL
      description: Provide a link of where the game can be obtained. (No piracy!)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### WAD Version
  - type: dropdown
    id: wad
    attributes:
      label: WAD Version
      multiple: true
      description: Select the WAD version of the game. Can be multiple if the game has multiple different versions.
      options:
        - WAD Version 8
        - WAD Version 9
        - WAD Version 10
        - WAD Version 11
        - WAD Version 12
        - WAD Version 13
        - WAD Version 14
        - WAD Version 15
        - WAD Version 16
        - WAD Version 17
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Tested on
  - type: dropdown
    id: platform
    attributes:
      label: Butterscotch Target
      multiple: true
      description: Select the platform that you tried using to run the game.
      options:
        - Desktop (Windows, macOS, Linux)
        - Web (WASM)
        - PlayStation 2
        - PlayStation 3
        - Another unofficial port
    validations:
      required: true
